const songDataEn = [
  [
    {
      id: 0,
      nick: "Coolio",
      name: "Leon Ivey-Jr.",
      track: "Gangsta’s Paradise",
      description: `American rapper. He became widely known in the mid-1990s for his albums It Takes a Thief, Gangsta's Paradise and My Soul. His song "Gangsta's Paradise" became an international hit and wona Grammy Award.`,
      image: "./assets/img/coolio.jpg",
      audio: "./assets/audio/Coolio.mp3",
    },
    {
      id: 1,
      nick: "Eminem",
      name: "Marshall Bruce Mathers III",
      track: "My Name Is",
      description: `Is one of the best-selling music artists in the world, as well as the best-selling artist of the 2000s. He is named one of the greatest musicians of all time by many magazines, including Rolling Stone, which placed Eminem at number 83 on its list of the 100 Greatest Artists, as well as at number 91 on its list of the 100 Greatest Songwriters of All Time.`,
      image: "./assets/img/eminem.jpg",
      audio: "./assets/audio/eminem-my-name-is.mp3",
    },
    {
      id: 2,
      nick: "DMX",
      name: "Earl Simmons",
      track: "Ruff Ryders' Anthem",
      description: `American rapper and actor. Five of his albums in a row have debuted at number one on the Billboard 200 chart, an unprecedented phenomenon. DMX has also appeared in several films. Over the course of his career, DMX has sold 74 million albums worldwide.`,
      image: "./assets/img/dmx.jpg",
      audio: "./assets/audio/DMX-ruff-ryders.mp3",
    },
    {
      id: 3,
      nick: "2Pac",
      name: "Tupac Shakur",
      track: "California Love",
      description:
        "A hip-hop-artist, producer and actor from Harlem, New-York, and later из Oakland, California. He is one of the most influential hip-hop artists in history. As of 2015, more than 80 million Tupac Shakur recordings have been sold worldwide. His double studio album All Eyez on Me, as well as a compilation of hits, are among the best-selling albums in the United States`",
      image: "./assets/img/2pac.jpg",
      audio: "./assets/audio/2Pac-california-love.mp3",
    },
    {
      id: 4,
      nick: "M. C. Hammer",
      name: "Stanley Kirk Berel",
      track: "U Can't Touch This",
      description: `The first album released on an independent label sold 60,000 copies, which attracted the interest of Capitol Records. They re-released it with minimal changes under the title Let's Get It Started. The album sold three million copies and brought the rapper fame. In 1990, MC Hammer achieved the greatest popularity and became the first artist in hip-hop to receive a diamond disc (over 10 million albums sold).`,
      image: "./assets/img/mc-hammer.jpg",
      audio: "./assets/audio/cant-touch-this.mp3",
    },
    {
      id: 5,
      nick: "Snoop Dogg",
      name: "Calvin Kordozar Broadus-Jr.",
      track: "Snoop Dogg - Still D.R.E",
      description: `American rapper, producer and actor. Snoop Dogg started his career in 1992 after meeting DJ and producer Dr. Dre.  Snoop is best known as an MC in the West Coast hip hop scene and one of Dr. Dre's proteges. His famous expression is " Fo 'shizzle, my nizzle", which means for sure my nigga (of course, my nigga). To date, Snoop's albums and singles have sold 20 million copies worldwide.`,
      image: "./assets/img/snoop.jpg",
      audio: "./assets/audio/Snoop-dogg-Still-Dre.mp3",
    },
  ],
  [
    {
      id: 0,
      nick: "Teriyaki Boyz",
      name: "Wise, Nigo, etc.",
      track: "Tokyo Drift",
      description: `A Japanese hip-hop group, consisting of rappers Ilmari and Ryo-Z from the group Rip Slyme, Verbal from M-Flo, rapper Wise and Nigo, DJ and founder of the popular Japanese brand A Bathing Ape. The band has collaborated with such famous artists as Kanye West, Pharrell, Busta Rhymes and Big Sean. Two of the band's tracks ("Tokyo Drift (Fast & Furious) "and" chō L A R G E") were featured on the soundtrack to the movie Triple Fast and Furious.`,
      image: "./assets/img/Teriyaki_Boyz.jpg",
      audio: "./assets/audio/tokyo-drift.mp3",
    },
    {
      id: 1,
      nick: "Evanescence",
      name: "Amy Lee and Ben Moody",
      track: "My Immortal",
      description: ` "My Immortal" is the third single by American rock-band Evanescence. The song was included in the album Fallen. At the 47th Grammy Awards, she was nominated for Best Pop Vocal Performance. It reached number seven in the United States and the United Kingdom, number one in Portugal, and spent twenty weeks in the top five in Canada. In Australia, the single reached number seven in sales in 2004`,
      image: "./assets/img/evanescence.jpg",
      audio: "./assets/audio/my-immortal.mp3",
    },
    {
      id: 2,
      nick: "Marius",
      name: "Marius Nedelku",
      track: "Rain",
      description: `Before starting his musical career, Marius worked as a fitness instructor and manager, but showed musical talent from childhood. In 2002, he gave a young DJ Adrian Claudio Segna to listen to his recordings, after which he invited Marius to a casting session and took him to the band Akcent (Accent). In 2008, Marius decided to devote all his energy to a solo career and left the band Akcent on April 16, 2008. In the summer of 2009, his song " Rain "(feat. Giulia), and in the summer of 2010`,
      image: "./assets/img/marius.jpg",
      audio: "./assets/audio/rain.mp3",
    },
    {
      id: 3,
      nick: "Eminem",
      name: "Marshall Bruce Mathers III",
      track: "Mockingbird",
      description: `Mockingbird is a song by Eminem from his fifth studio album, Encore. It debuted at #11 on the US music charts and #4 in the UK. She was nominated for a Grammy in the category"Best Solo Rap Performance". Included in лучшие хиты Eminem's greatest hits Curtain Call: The Hits.`,
      image: "./assets/img/eminem.jpg",
      audio: "./assets/audio/Mockingbird.mp3",
    },
    {
      id: 4,
      nick: "t.A.T.u.",
      name: "Yulia Volkova and Elena Katina",
      track: "I'm crazy",
      description: `Tatu is the most successful Russian pop group that has achieved worldwide popularity. Their singles, both in English and Russian, topped the charts in Russia, Australia, Great Britain, Germany, the United States and other countries. Their debut English-language single "All the Things She Said" became one of the most successful singles of the year and topped the major music charts around the world. Tatu is the first and only Russian band to receive the IFPI award for the number of albums sold.`,
      image: "./assets/img/tatu.jpg",
      audio: "./assets/audio/tatu-soshla.mp3",
    },
    {
      id: 5,
      nick: "Bon Jovi",
      name: "Jon Bon Jovi et al.",
      track: "It’s My Life",
      description: `Bon Jovi has released 15 studio albums, six compilations and two live albums. In total, their albums have sold 130 million copies. They played more than 2,600 shows in 50 countries in front of an audience of 34 million and were inducted into the UK Music Hall of Fame in 2006. In 2004, the band won an award for Musical Achievement at the American Music Awards, and in 2009, Jon Bon Jovi and Richie Sambora were inducted into the Songwriters Hall of Fame.`,
      image: "./assets/img/Bon-Jovi.jpg",
      audio: "./assets/audio/its-my-life.mp3",
    },
  ],
  [
    {
      id: 0,
      nick: "Alex Hepburn",
      name: "Alexandra Hepburn",
      track: "Under",
      description: `Alex Hepburn is a British singer and songwriter. She released her self-titled EP in June 2012. In April 2013, she released her debut album Together Alone`,
      image: "./assets/img/hepburn.jpg",
      audio: "./assets/audio/under.mp3",
    },
    {
      id: 1,
      nick: "Ellie Goulding",
      name: "Elena Jane Golding",
      track: "Love Me Like You Do",
      description: `British singer and songwriter. She gained fame after taking first place in the BBC Sound of 2010 poll and winning the Critics ' Choice Award at the 2010 BRIT Awards. After signing with Polydor Records in 2009, she released her first EP, "An Introduction to Ellie Goulding", followed by her debut studio album,"Lights".`,
      image: "./assets/img/elli-golding.jpg",
      audio: "./assets/audio/love-me.mp3",
    },
    {
      id: 2,
      nick: "Coldplay",
      name: "K. Martin, D.. Buckland et al.",
      track: "Hymn For The Weekend",
      description: `British rock band. Having started playing in January 1996, Coldplay achieved real success in the world in 2000, after the release of their second single" Yellow " from the album Parachutes, which broke into the top of all charts in the UK and the United States. Coldplay's albums have sold over 80 million copies. Coldplay has won a Grammy Award seven times for their albums Parachutes, A Rush of Blood to the Head and Viva la Vida or Death and All His Friends.`,
      image: "./assets/img/cooldplay.jpg",
      audio: "./assets/audio/hymn-weekend.mp3",
    },
    {
      id: 3,
      nick: "Sage the Gemini",
      name: "Dominic Wynn Woods",
      track: "GDFR",
      description: `Best known for his синглами2013 singles "Gas Pedal"года, which peaked at # 29on места the Billboard Hot 100, and "Red Nose", as well as his role in сингле Flo Rida 2014 's 2014 single "Going Down For Real". (GDFR)".[4] His debut studio album, Remember Me, was released on Republic Records in March 2014. He is a member of the Bay Area hip hop collective The HBK Gang and is the only member of the group, along with singer Kelani, to have signed to a major label.`,
      image: "./assets/img/gemini.jpg",
      audio: "./assets/audio/GDFR.mp3",
    },
    {
      id: 4,
      nick: "Katy Perry",
      name: "Katy Perry",
      track: "Dark Horse",
      description: `Is a song recorded by American singer Katy Perry for her fourth studio album, Prism. To date, "Dark Horse" is the best-selling female song in the United States and one of the best-selling songs in the world.`,
      image: "./assets/img/perry.jpg",
      audio: "./assets/audio/dark-horse.mp3",
    },
    {
      id: 5,
      nick: "Imagine Dragons",
      name: "Imagine Dragons and others",
      track: "Sucker for Pain",
      description: `"Sucker for Pain is a song, recorded by American rappers Lil Wayne, Wiz Khalifa, Logic, Ty Dolla Sign and bands Imagine Dragons and X Ambassadors, which was included in the soundtrack of the movie "Отряд Suicide Squad". The single was released on June 24 2016 , 2016 лейбламиby Atlantic Records and Warner Bros. Records. On the same day, a video clip for the song was released, using footage from the movie "Suicide Squad". By September 2016, the single had sold approximately 355,000 copies in the United States`,
      image: "./assets/img/sucker-for-pain.jpg",
      audio: "./assets/audio/sucker-for-pain.mp3",
    },
  ],
  [
    {
      id: 0,
      nick: "Vivaldi",
      name: "Antonio Lucho Vivaldi",
      track: "Concerto No. 2 in G minor",
      description: `He left a huge and diverse compositional legacy: operas, oratorios, instrumental and chamber music. Vivaldi is considered one of the greatest representatives of the Italian violin art of the XVIII century. During his lifetime, he was widely recognized as a violinist throughout Europe. Vivaldi's fame as a composer was great during his lifetime, but after his death, his fame began to fade.`,
      image: "./assets/img/vivaldi.jpg",
      audio: "./assets/audio/vivaldi.mp3",
    },
    {
      id: 1,
      nick: "Chopin",
      name: "Fryderyk Chopin",
      track: "Spring Waltz",
      description: `Author of numerous works for piano. He reinterpreted many genres: revived the prelude on a romantic basis, created a piano ballad, poetized and dramatized dances-mazurka, polonaise, waltz; turned the scherzo into an independent work. He enriched harmony and piano texture; combined classical form with melodic richness and imagination.`,
      image: "./assets/img/chopin.jpg",
      audio: "./assets/audio/chopin.mp3",
    },
    {
      id: 2,
      nick: "Wolfgang Mozart",
      name: "Johann Chrysostom Wolfgang Amadeus Mozart",
      track: "Rondo: Allegro",
      description: `Unlike many composers of the 18th century, Mozart not only worked in all the musical forms of his time, but also achieved great success in them. Many of his compositions are recognized as masterpieces of symphonic, concert, chamber, opera and choral music. Along with Haydn and Beethoven, he is one of the most important representatives of the Viennese classical School.`,
      image: "./assets/img/mocart.jpg",
      audio: "./assets/audio/mocart.mp3",
    },
    {
      id: 3,
      nick: "Tchaikovsky",
      name: "Pyotr Ilyich Tchaikovsky",
      track: "March(from the Nutcracker ballet)",
      description: `Tchaikovsky's legacy is represented by different genres: These include ten operas, three ballets, seven symphonies (six numbered and the Manfred Symphony), 104 romances, a number of program symphonic works, concertos and chamber-instrumental ensembles, choral compositions, cantatas, piano miniatures and piano cycles. His work is an extremely valuable contribution to the world musical culture and, along with the work of his contemporaries, the composers of the Mighty Handful, marks a new stage in the development of Russian music.`,
      image: "./assets/img/chaikovskii.jpg",
      audio: "./assets/audio/chaikovskii.mp3",
    },
    {
      id: 4,
      nick: "Beethoven",
      name: "Ludwig van Beethoven",
      track: "Moonlight Sonata",
      description: `Beethoven is a key figure of classical music in the period between classicism and Romanticism, one of the most performed composers in the world. He wrote in all the genres that existed in his time, including opera, music for dramatic performances, choral compositions. The most significant in his legacy are considered instrumental works: piano, violin and cello sonatas, concertos for piano, for violin, quartets, overtures, symphonies.`,
      image: "./assets/img/betkhoven.jpg",
      audio: "./assets/audio/betkhoven.mp3",
    },
    {
      id: 5,
      nick: "Bang",
      name: "Johann Sebastian Bach",
      track: "Prelude №15",
      description: `Bach is the author of more than 1000 pieces of music in all major genres of his time (except opera). Bach's creative heritage is interpreted as a generalization of the Baroque musical art. A staunch Protestant, Bach wrote much sacred music. His St Matthew Passion, h-moll Mass, cantatas, instrumental arrangements of Protestant chorales are recognized masterpieces of world music classics. Bach is known as a great master of polyphony, and in his work Baroque polyphony reached its peak.`,
      image: "./assets/img/bakh.jpg",
      audio: "./assets/audio/bakh.mp3",
    },
  ],
  [
    {
      id: 0,
      nick: "Imanbek",
      name: "Imanbek Maratovich Zeikenov",
      track: "Belly Dancer",
      description: `Kazakh DJ and music producer. In 2019, he became world-famous for his remix of Saint Jhn's song "Roses", for which he received the Grammy 2021 music Award, becoming the first musician from Kazakhstan to receive a Grammy, as well as the first musician from the CIS and the former USSR to receive a Grammy in the non-classical music category.`,
      image: "./assets/img/imanbek.jpg",
      audio: "./assets/audio/dancer.mp3",
    },
    {
      id: 1,
      nick: "Minnelli",
      name: "Luisa Ionela Luca",
      track: "Rampampam",
      description: `The international hit "Rampampam" was released on March 18 2021 , 2021 in Romania and Russia by Global Records. The single was written by Minnelli and Vicki Red. It took the first place in the official charts of Belarus, Bulgaria, the Czech Republic, Hungary, Lithuania and Russia, and took the second place in the charts of Romania, Poland and Ukraine. For the week ending August 28, 2021, "Rampampam" peaked at # 139 on the Billboard Global chart, excluding the United States.`,
      image: "./assets/img/minelli.jpg",
      audio: "./assets/audio/rampampam.mp3",
    },
    {
      id: 2,
      nick: "Masked Wolf",
      name: "Harry Michael",
      track: "Astronaut in the Ocean",
      description: `Australian rapper and singer. He gained popularity with the single "Astronaut in the Ocean". It was originally released in June 2019, before being re-released on Elektra Records on January 6, 2021. Upon re-release, the song achieved success, peaking at # 4 on the Australian ARIA Charts and # 6 on the US Billboard Hot 100`,
      image: "./assets/img/wolf.jpg",
      audio: "./assets/audio/astronaut.mp3",
    },
    {
      id: 3,
      nick: "Rihanna",
      name: "Robin Rihanna Fenty",
      track: "Lift Me Up",
      description:
        "Rihanna is one of the best-selling artists of all time, selling over 20 million album copies and 60 million singles. She is the youngest singer in the history of Billboard, who managed to top the Billboard Hot 100 chart fourteen times. Rihanna is the winner of eight Grammys, six American Music Awards, a special Icon Award, and eighteen Billboard Music Awards`",
      image: "./assets/img/rihanna.jpg",
      audio: "./assets/audio/rihanna.mp3",
    },
    {
      id: 4,
      nick: "David Guetta",
      name: "Pierre David Guetta",
      track: "Im Good (Blue)",
      description: `The track was recorded, performed and remixed several years before it went viral on TikTok in 2022. Rexa later re-recorded her vocals for the track before it was released as a single. It topped the charts in 20 countries such as Australia, Canada, Switzerland, Denmark, the Netherlands, Norway, Finland, Sweden and the United Kingdom.`,
      image: "./assets/img/good.jpg",
      audio: "./assets/audio/good.mp3",
    },
    {
      id: 5,
      nick: "Tom Odell",
      name: "Tom Peter Odell",
      track: "Another Love",
      description: `Tom Peter Odell is a British singer, musician and songwriter. His debut album, Long Way Down, was released on June 24, 2013. His second studio album, Wrong Crowd, was released on June 10, 2016. In October 2018, his third studio album Jubilee Road was released`,
      image: "./assets/img/love.jpg",
      audio: "./assets/audio/love.mp3",
    },
  ],
  [
    {
      id: 0,
      nick: "Sam Smith",
      name: "Samuel Frederick Smith",
      track: "Unholy",
      description: `Smith released his debut studio album In the Lonely Hour on May 26, 2014 via Capitol Records, along with the singles "Lay Me Down" (lead single), "Money on My Mind" (2nd single). In 2013 and 2014, he topped the UK charts three times with the singles La La La (Naughty Boy featuring Sam Smith), whose music video has over 1 billion views on YouTube, Money on My Mind and Stay with Me.`,
      image: "./assets/img/unholu.jpg",
      audio: "./assets/audio/unholy.mp3",
    },
    {
      id: 1,
      nick: "Chris Brown",
      name: "Christopher Maurice Brown",
      track: "Under The Influence",
      description: `American singer and actor. Brown released his debut album Chris Brown in late 2005 at the age of 16. The album included the single " Run It!", which topped the Billboard Hot 100 chart, making Brown the first African-American singer to have his debut single top the chart. The album has sold over two million copies`,
      image: "./assets/img/under-the-influence.jpg",
      audio: "./assets/audio/Under-The-Influence.mp3",
    },
    {
      id: 2,
      nick: "Rema",
      name: "Divine Ikubor",
      track: "Calm Down",
      description: `Nigerian rapper, musician and performer. He became famous with the release of the song "Dumebi". In 2019, he signed with Jonzing World, a subsidiary of Mavin Records. On September 7, 2022, Ryouma received the award on stage during his London concert, as his songs racked up 1 billion listens worldwide.`,
      image: "./assets/img/rema.jpg",
      audio: "./assets/audio/rema.mp3",
    },
    {
      id: 3,
      nick: "Blackpink",
      name: "Jisoo, Jenny, Rose and Lisa",
      track: "Pink Venom",
      description: `Blackpink became YG Entertainment's first female group since 2NE1 debuted in 2009. Their first five singles sold 113,000 digital copies in the United States, and all of their albums reached the top of the Billboard Digital Albums Chart; Blackpink reached the highest position for Korean female groups on the Social 50 chart.`,
      image: "./assets/img/pink.jpg",
      audio: "./assets/audio/pink.mp3",
    },
    {
      id: 4,
      nick: "Imagine Dragons",
      name: "Dan Reynolds et al.",
      track: "Bones",
      description: `American pop rock band formed in 2008 in Las Vegas, USA. They became known after releasing their debut studio album Night Visions in September 2012. American magazine Billboard named them the brightest new stars of 2013 and the biggest band of 2017`,
      image: "./assets/img/bones.jpg",
      audio: "./assets/audio/bones.mp3",
    },
    {
      id: 5,
      nick: "Shakira",
      name: "Shakira Isabel Mebarak Ripoll",
      track: "Monotonia",
      description: `Widely known as the most successful Latin American artist, who achieved success by the early 2000s in the Spanish-speaking and English-speaking music markets. Shakira has won many awards, including five MTV Video Music Awards, two Grammys, eight Latin Grammys, seven Billboard Music Awards, twenty-eight Billboard Latin Music Awards, and a Golden Globenomination.`,
      image: "./assets/img/shakira.jpg",
      audio: "./assets/audio/monotonia.mp3",
    },
  ],
];

export default songDataEn;
